### ISSUE TITLE
Hack the Opioid Crisis: Information Architecture, Branding and Assets

### ISSUE THREAD

**Issue by laveshaparker** [ProgressiveHackNight/project-ideas#11]
### What problem are we trying to solve?

There are two nation-wide Take Back Days held annually. This is a time for people to take their unused and unneeded prescription drugs to designated sites for free and environmentally-friendly disposal.  

There are a lot of efforts to fight back against the opioid crisis, but there is no recognizable branding for Take Back Day that can be used by the public advocates who work very hard to keep the public informed about the severity of this issue. We need a brand and branded assets to make available to these public advocates.

### Who will benefit (directly and indirectly) from this project?

Public advocates who are fighting the opioid crisis stand to benefit directly from this project. We will provide them with useful materials (downloadable flyers to pass out, branded assets, etc.) to really get a lot of great work done.

### Where can we find any research/data available/articles?

The New York Attorney General's office has provided publicly available data [here](https://github.com/NYAG/Takeback_Day_Hackathon). You might also want to read the [DEA's official Take Back Day site](https://takebackday.dea.gov/) for exact information.

#### Creatives and Designers
We need a brand. We want Take Back Day to have a completely new connotation. There is currently an air of "giving prescription drugs to law enforcement officials, and watching them take it from you." We would like to change this into a more hopeful and cause-based endeavor. i.e. "April 28th is for ______" (where the blank can be "Billy" or "The Environment". Also, Take Back Day is on April 28th this year).

### What are the next steps (validation, research, coding, design)?
We need to aggregate the most important information for this event, and understand what information public advocates might need to disseminate.

We also need to discuss how this should be branded so it comes across as a source of hope for a country without this severe opioid usage.

### How can we contact you outside of Github(list social media or places you're present)?
_Add your name here if you plan to stay on with this project through the March 11 HackDay!_

### Sources
The information in this issue is based off of ideas generated in our Pre-HackDay event. For more context and information on the people behind these ideas, please check out their issues!
[Leveling Up Outreach](https://github.com/ProgressiveHackNight/project-ideas/issues/7)
[Take Back Day Toolkit](https://github.com/ProgressiveHackNight/project-ideas/issues/6)

----
If you get stuck at any point, feel free to reach out to the leadership team with an email to steering@progressivehacknight.org or come find an organizer at a HackNight. We're here to help bring great ideas to life!

**Comment by ibrand** [comment]
This project ended up providing the branding assets that guided the the work for #9 and also appeared at a [press conference](https://ag.ny.gov/press-release/ag-schneiderman-launches-new-website-help-new-yorkers-safely-dispose-unused-opioids) that the attorney general's office held for Take Back Day.
