### ISSUE TITLE
Help ProPublica Find Missing White House Financial Disclosures 

### ISSUE THREAD

**Issue by moajzashahab** [ProgressiveHackNight/project-ideas#18]
### What problem are we trying to solve?

Figure out which people in the White House staff are missing financial disclosure forms.

### Who will benefit (directly and indirectly) from this project?

ProPublica because they'll have an easier time knowing which leads to pursue but really all of us because then we'll know which people in the White House have conflicts of interest. 

### Where can we find any research/data available/articles?

https://www.propublica.org/getinvolved/white-house-financial-disclosures-names

### What help is needed at this time?

It's explained in the linked article. 

### What are the next steps (validation, research, coding, design)?

Click through on the article and do some research to compare which staffers aren't on the list they compiled.

**Comment by rapicastillo** [comment]
Hey @moajzashahab I've added you in our Breakout Group leads list! :)
