### ISSUE TITLE
Website for Florida voter-registration volunteers (visitors)

### ISSUE THREAD

**Issue by roryrabbitfield** [ProgressiveHackNight/project-ideas#43]
### What problem are we trying to solve?

Help visitors to Florida (esp. from NY) easily connect with local community groups to volunteer on voter registration. 

Based in NYC, Water For Grassroots supports community organizing groups doing long-term organizing in the swing states. Last year we partnered with organizations in Florida to help pass a constitutional amendment re-enfranchising people who have past felony convictions. Amendment 4 was approved by a 2-to-1 margin -- and despite Republican attempts to undermine it, nearly a million newly eligible Floridians could register to vote right now, without meeting any further conditions. Now we’re supporting Florida community organizations in their efforts to register as many new voters as possible in the coming year-- particularly these returning citizens, and other voters in underrepresented communities.

Since most voter-registration work is done in-person, the Florida group we worked with most closely last year (New Florida Majority, a Center for Popular Democracy affiliate) told us that the most useful thing we could do would be outreach to New Yorkers who’ll be visiting Florida, to invite them to volunteer on voter registration while they’re in the state.  With a few million New Yorkers visiting Florida each year, if we can involve a tiny fraction of that number it could mean hundreds or thousands of additional volunteers. 

After discussions with NFM & several other Florida groups active in voter registration, we're planning to set up a website for visitors to the state, to connect them with opportunities to volunteer on voter registration--for an afternoon, a day, or more. 

If someone is planning a visit to Florida, they'd be able to go to this site, select the area where they'll be, & get information on how to connect with groups doing voter registration there or nearby. We're already in touch with more than a dozen Florida organizations that would like to be listed.

### Who will benefit (directly and indirectly) from this project?

Florida communities that are under-represented in the political process.
Progressive community-based organizations in Florida.
Progressive candidates in Florida
Anyone who wants to help defeat Trump

### Where can we find any research/data available/articles?

Can provide more info on request (on Amendment 4, Florida politics, our local Florida organizing partners, etc.).  For our project this question’s a little broad so hard to respond right now. 

### What help is needed at this time?

Water For Grassroots has created a 3-person website team to work on this project, and we’ve put together some initial thoughts on specs for this website (see below). But only one of us has tech experience, & none of us are designers/developers.  So we need one or more skilled partners who can build the site!

Rory Bernstein is a Water For Grassroots volunteer who’s a project manager with website development/design background.  As work on the site gets underway, she can be the point person for website specs and related communication, to keep everything on track.

### What are the next steps (validation, research, coding, design)?

Here are our initial thoughts on website specs. Some are essential, others would be very useful but not required for an initial launch.  These need some further work, then site needs to get built:

At the most basic level, we'll need a site that covers the following points:
•	Provides an overview of our goal (to register new voters in FL)
•	Gives basic info on the FL groups that need help (description, website URL, type of help needed, etc)
•	Allows the user to sort/view the info about these groups according to various criteria:
o	geography (by county or city, or by radius distance from a specific location)
o	for some groups, date of voter registration events
•	In order to help people find the best group for their needs, we imagine allowing the user to input some data in order to filter the listing of the groups to match their skills & interest: 
o	whether they speak Spanish or Kreyol (necessary for some groups)
o	whether they want to help register voters in person, help with data entry & other office tasks, or both
o	location where the volunteer will be visiting. 
•	Asks users for their email address so we can follow up with them 
•	Website will ultimately need to be in both English & Spanish. Might want to add Kreyol later, depending on needs & resources)
We'll need a basic CMS that allows our volunteers to update info on the site without help from a developer.  

We realize that there are various approaches to getting this done, from the very simple (no searching/filtering, just statically displaying the info in a really easy to use format) to the more complex (showing the groups' locations on a real map, allowing the user to enter search/filter criteria to limit the information to just the most relevant results). 

We're hoping to get a functional site set up by mid-September, if that's at all possible. 

----

#### Checklist for NEW ideas :baby:
Hey, you're official! You're now part of the growing Progressive HackNight community. Here's a few things to get started (a couple you've probably already done).

- [x] Create this idea issue
- [x] Flesh out the who, where, and what questions above
- [x] Join our [Slack](https://progressivehacknight.slack.com)
- [x] Join the [#project-leads](https://progressivehacknight.slack.com/messages/CFLCLB1PV/) channel. 
- [ ] Ping an organizer to get started (The organizer in charge of onboarding new projects will be listed in the channel topic)

#### Checklist for ACTIVE projects :fire:
Let's get this project started! When this idea starts taking off, the Progressive HackNight Team will start helping this project's lead(s) out with project management and connecting you to resources you may need. To get there, please complete and check off the following:

- [ ] Update your project at least once a month.  This can be either an update on this issue, a ping in the project-ideas channel, rsvp-ing to hacknight, or a conversation with one of the organizers managing project progress (the one listed in the channel topic). 
  - It's ok even if your update is just "nothing new happened this month" or "we saw a small increase in traffic to our app this month". If nobody hears from you at all in more than one month, we may mark it as `abandoned` so that others can pick up this idea and run with it.
- [ ] Create a [GitHub repository](https://github.com/new) and Slack channel for work.
- [ ] [Create issues](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/project-set-up-for-collaboration-with-github/#assignment--add-your-first-issue) to describe each task that you plan to do or need help with and how a contributor can get started on that task. You might start and stop a lot, so consider issues as your to-do list.
- [ ] Create a [team](https://help.github.com/articles/creating-a-team/) for your core contributors
  - This will make it easier for you to manage your github repo access. People on a team have the same level of access. Admin access will allow your trusted contributors to make changes as needed. 
  - You can remove and add people to your team as needed. 
  - Note: You can also allow collaborators outside of your team and give them more limited access.
- [ ]   Create a [Google Drive](https://drive.google.com), [Dropbox](https://www.dropbox.com/), or other cloud storage to share larger files
  - Github and Data.World are good for code and data, respectively, especially when you need version control. But they're not good for very large files, documentation, articles, etc. A cloud storage option will allow you to easily share, create, and collaborate on documents with your team and help organize ideas and thoughts.
  - Doing this early on can help your team stay organized and to onboard new contributors who wouldn't have access to files you all have shared over email.

If you get stuck at any point, feel free to reach out to the leadership team in the slack channel or with an email to organizers@progressivehacknight.org or come find an organizer at a HackNight. We're here to help bring great ideas to life!

**Comment by water4grassroots** [comment]
@water4grassroots Hello Peter.

**Comment by roryrabbitfield** [comment]
@peterhogness Hello again.

**Comment by cgalbiati** [comment]
github repo for the project: https://github.com/ProgressiveHackNight/water-for-grassroots,

**Comment by olliebeannn** [comment]
Hey @roryrabbitfield ! Is this still an active project? If so I'd love to learn more about it and the kind of support you're looking for right now

**Comment by ibrand** [comment]
Congrats on finishing the project @roryrabbitfield ! Here's a link to the finished site: https://www.helpfloridaregister.org/

Closing this issue due to its completion
