### ISSUE TITLE
Knowing where, when and how to drop your meds! 

### ISSUE THREAD

**Issue by annadph** [ProgressiveHackNight/project-ideas#5]
Addressing Goal #1: Lowering the barrier

Overview:
https://docs.google.com/document/d/1NFMYGpGEK3N6gFlV5JgbBYj6R2sgk3H-jSTE8dY6jTs/edit#

Presentation:
https://docs.google.com/presentation/d/1G5G4YWI5u4GNNGr_7BRNyo8tdDDWE1WvSI3gdkqgOEc/edit#slide=id.g3420cd0adb_0_0

Team:
Daniel Spencer (full stack dev) - daniel.patrick.spencer@gmail.com
Carlos Merced (front end dev) - mail.merced@gmail.com
Annie Hirshman (designer) - anniehirshman@gmail.com
Anna de Paula Hanika (product) - annadph@gmail.com
Daeha Ko (IT) - daehako@gmail.com

**Comment by ibrand** [comment]
This was an idea that came out of the February Pre-Hack for Take Back Day event. That event was an ideation session. The ideas went on to become fleshed out projects at Hack the Opioid Crisis which was an all day Hack event.

**This idea went on to influence #8, #9, #10, and #11**
